### ISSUE TITLE
Warning: Unable to create restoration in progress marker file

### ISSUE THREAD

**Issue by arden** [square/SuperDelegate#13]
2017-02-12 14:29:42.992 SampleDelegate[29473:1815744] Warning: Unable to create restoration in progress marker file
why? i'm run it on xcode 8.2.1

**Comment by dfed** [comment]
There's not nearly enough information here for us to diagnose.

What are you trying to do? When did this start happening? Have you been able to reproduce this in a sample app?

**Comment by dfed** [comment]
Haven't heard back. Closing out.

**Comment by aniketlokhande07** [comment]
hello,
i want to do change camera setting means enable camera from . i m goes in setting through application and after enable camera access i want to come back on that same state of application.

for that i implement 
follwing methods
func application(_ application: UIApplication, willFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey : Any]? = nil) -> Bool {
        return true
    }


    func application(_ application: UIApplication, shouldRestoreApplicationState coder: NSCoder) -> Bool {
        return true
    }


    func application(_ application: UIApplication, shouldSaveApplicationState coder: NSCoder) -> Bool {
        return true
    }
 func application(_ application: UIApplication, willEncodeRestorableStateWith coder: NSCoder) {
        
        coder.encode(sessionID, forKey: "sessionID")
        coder.encode(token, forKey: "token")
        
    }
    func application(_ application: UIApplication, didDecodeRestorableStateWith coder: NSCoder) {
        
        if let sessionID = coder.decodeObject(forKey: "sessionID")
        {
            self.sessionID = sessionID as! String
            
        }
        if let token = coder.decodeObject(forKey: "token")
        {
           self.token = token as! String
        
        }
      
        
        
    }
    func application(_ application: UIApplication, viewControllerWithRestorationIdentifierPath identifierComponents: [Any], coder: NSCoder) -> UIViewController? {
        if #available(iOS 10.0, *) {
            let viewController = ViewController()
                return viewController
        } else {
            // Fallback on earlier versions
        }
        return nil
    }
    

in appdelegate class

i m run application this functionality doesn't work 
but at start of application 
2017-06-20 11:22:31.973 application[57560:2433424] Warning: Unable to create restoration in progress marker file

how to solve restoration process to come back to application

**Comment by dfed** [comment]
Are you conforming to `StateRestorationCapable` in your AppDelegate class @aniketlokhande07? Kinda looks like you're not.
