### ISSUE TITLE
setup(mainWindow:) shouldn't set UIWindow's bounds on iOS9+

### ISSUE THREAD

**Issue by TadeasKriz** [square/SuperDelegate#14]
When setting UIWindow's bounds to `UIScreen.main.bounds` it breaks apps on iPads with iOS 9 and higher. This is caused because of the multitasking feature introduced in iOS 9. Setting those bound make the app appear under the status bar. Having just `makeKeyAndVisible` results in correct behavior.

**Comment by dfed** [comment]
Seems reasonable. What's the `bounds` on iPads? Is it `.zero`?  Could we just set the bounds if it isn't zero?

**Comment by dfed** [comment]
Revisiting this: obviously the `bounds` are not `.zero`. Are the bounds just set for us? Or does the client need to retrieve it somehow?

**Comment by TadeasKriz** [comment]
As far as I understand Apple's docs, you shouldn't set UIWindow's bounds and also should use its bounds when you need to work with bounds of the app (instead of using UIScreen.main.bounds). I'll do a bit more investigation on the bounds value later today and let you know.

**Comment by benjohnde** [comment]
Any news on that @TadeasKriz ?

**Comment by benjohnde** [comment]
I just did a bit of testing. Sadly we do not have any devices supporting iOS < 9. As Apple discontinued those, it may be okay to set the minimum deployment target to iOS 9. As far to my knowledge, if we do this, we do not need to set the `UIWindow` bounds. Here, it works for every iPhone / iPad which are currently supported by Apple.
