### ISSUE TITLE
Emphasize UIApplicationDelegate protocol requirements

### ISSUE THREAD

**Issue by benjohnde** [square/SuperDelegate#20]
Adjust sample project to emphasize UIApplicationDelegate protocol requirements.

In the current example project window is defined as:

```
  let window = UIWindow()
```

If I am using some libraries like [SVProgressHUD](https://github.com/SVProgressHUD/SVProgressHUD) which access the current `UIWindow` via the following selector `UIApplication.shared.delegate?.window` they all crash as this invocation returns nil.

Hence, I propose to update the sample project to meet those protocol requirements.

**Comment by dfed** [comment]
It's up to adopting applications to declare a `window` property and feed it to the `setup(mainWindow: UIWindow)` method on SuperDelegate, but this feels like a reasonable change since we could be leading people towards some pain.
