### ISSUE TITLE
SuperDelegate should not contain test helpers

### ISSUE THREAD

**Issue by benjohnde** [square/SuperDelegate#23]
I suggest to move the method `testing_resetAllData()` from `Sources` to `Tests`. Without having deep dived into that, I guess that we could also add this functionality via extension :).

**Comment by dfed** [comment]
You're right. If we made
```
private var applicationDidBecomeActiveListener: NSObjectProtocol?
private var applicationWillEnterForegroundListener: NSObjectProtocol?
private var applicationDidEnterBackgroundListener: NSObjectProtocol?
```
`internal` instead of `private` we could move the `testing_resetAllData()` method into `Tests` via an extension. That said, given that `testing_resetAllData()` is already `internal` and therefore not accessible to consumers of the SDK, what do we accomplish by moving the code?

**Comment by benjohnde** [comment]
From a consumer's point of view, nothing changes. As you stated correctly, the code is not accessible. I strongly believe that test methods, properties, helpers should only reside in the `Tests` folder to which they belong in favor of a more clear separation between actual implementation and tests (from a developer's point of view).

**Comment by dfed** [comment]
The struggle I have here is that an `internal func testing_*()` method should clearly not be called/used by other non-testing code within `SuperDelegate`, while an `internal var *Listener` property doesn't feel as clearly off-limits. I'd rather err on the side of making intended usage clear. Does that make sense? I'm open to ways of making the listener property internal, but still making it clear it should be considered private to the class.

I've always hoped that `@testable` would some day allow me to reference `private` methods/variables... but I think that hope is in vain.

**Comment by dfed** [comment]
There is no plan to address this issue. Closing.
