### ISSUE TITLE
[1.0] Adopt UIUserNotification* API from iOS 10 SDK

### ISSUE THREAD

**Issue by dfed** [square/SuperDelegate#3]
Today, SuperDelegate does not utilize new UIUserNotification API that redefines how developers:
- Request user notification permissions
- Receive user notifications (both local and remote)

To ensure that user notifications continue to work well on iOS 10, we need to adopt this API. The end goal is to provide a simple API for user notifications that works the same way on iOS 8, 9 and 10. Thankfully, SuperDelegate has already broken out concept of UserNotifications via the `UserNotificationCapable` protocol. In order to have a consistent API on iOS 8, 9, and 10, we'll need to define a new `UserNotification` struct that can be initialized with:
- A `UIUserNotification` for iOS 10+
- A `[NSObject : AnyObject]?` for iOS 8 and 9

We will also need to create a `UserNotificationActionCapable` that will likely subsume the `LocalNotificationActionCapable` and `RemoteNotificationActionCapable` protocols.

As we learn more about the UIUserNotification API, we'll put additional learnings here.

**Comment by dfed** [comment]
Working on an iOS-10 only API on my fork: https://github.com/dfed/SuperDelegate

May back port it if there is enough interest.

**Comment by dfed** [comment]
Spent much of the day yesterday playing with the new APIs. iOS 10 has nerfed `launchOptions` in `applicationDidFinishLaunching`: there is no way to know that you were launched due to a locally posted `UNUserNotification` (formerly `UILocalNotification`) without relying on the now-deprecated `UIApplicationLaunchOptionsKey.localNotification`.

This change means that `loadInterface(launchItem: LaunchItem)` might be called with `.none` but the app may then receive a `didReceive(notification: UserNotification)` (not written yet) call within a few milliseconds. That is pretty awful, and is making me reconsider how we implement SuperDelegate's core promise that you'll only be notified of a single `LaunchItem` once.

Given the changes in the `AppDelegate` and `UserNotification` API in iOS 10, it seems that Apple is prescribing that the app launch flow should be:
- Launch to splash screen. Use time on splash screen to load any necessary resources & wait for app delegate calls
- If after 200ms no `AppDelegate` calls have been received, proceed to normal app landing screen
- If an `AppDelegate` call is received, process it and show the right UI from the splash screen.

200ms in the above example is a straw man – that time should be a balance between the average time between `applicationDidFinishLaunching` and an `AppDelegate` call (which I still need to measure), and how long you want your customer to see your splash screen.

So my current thinking for a redux of the SuperDelegate API for iOS 10 boils down to two proposals. If you have a preference, please say so (and why) in this thread! Also happy to entertain additional proposals.

**Proposal 1**

Add a new public property to `class SuperDelegate`: 

```
/// The time delay between calls to loadSplashScreen() and loadInterface(launchItem:).
/// This delay is used to consolidate AppDelegate API calls received after loadSplashScreen()
/// into a single `LaunchItem` that will then be passed to `loadInterface(launchItem:)`. 
/// Use this time to load resources from disk or the network.
public var delayBetweenLoadSplashScreenAndLoadInterface: TimeInterval = 0.200
```

And the `ApplicationLaunched` protocol will have 3 methods:

```
public protocol ApplicationLaunched {
    /// Very first method that SuperDelegate calls on launch. Guaranteed to only be called once.
    func setupApplication()
    /// Called when the app launches. Guaranteed to only be called once.
    func loadSplashScreen()
    /// Called `delayBetweenLoadSplashScreenAndLoadInterface ` after loadSplashScreen().
    /// Guaranteed to only be called once.
    func loadInterface(launchItem: LaunchItem)
}
```

**Proposal 2**

Strike the entire `LaunchItem` concept and remove the `LaunchItem` enum. `ApplicationLaunched` becomes:

```
public protocol ApplicationLaunched {
    /// Very first method that SuperDelegate calls on launch. Guaranteed to only be called once.
    func setupApplication()
    /// Called when the app launches. Guaranteed to only be called once.
    func loadSplashScreen()
}
```

From there, we forward `AppDelegate` callbacks for `UserNotification`s, `ShortcutItem`s, `NSUserActivity`s, and `URLToOpen`s like we do today and let the receiving app handle timing.

**Comment by TadeasKriz** [comment]
Hey, from your description I like the first proposal more. Seems to me like it would remove a lot of boilerplate from apps.

**Comment by gfontenot** [comment]
Has there been any progress on this?

**Comment by benjohnde** [comment]
I also favor the first proposal. Any news on that? I would like to help out. Maybe we could split up this issue into two or more smaller tasks?

**Comment by dfed** [comment]
I'm leaving this one in the hands of @efirestone, @pwesten, @ericmuller22, and @nickentin.

Another option (**Proposal 3**) could be to just remove UserNotifications from the `LaunchItem` enum, and basically strike UserNotifications from `SuperDelegate` entirely — the new UserNotifications API adds a lot of the niceties that we added here. We'd have to drop iOS 9 support in a release that included this change, and just support iOS 10 plus.

After sitting on this awhile, Proposal 1 feels a bit too hacky and vulnerable to failure. Proposal 2 is an invitation for adopting apps to build boilerplate (not what we want). Proposal 3 feels like our best bet at this point, but I'm open to opposing views.

**Comment by MatrixSenpai** [comment]
Hey guys

There may be another solution to this issue. Maintain a branch with a snapshot of the project to-date on a branch titled iOS-9.0 and drop support. Master should contain iOS 10.0+ code, since that is most likely to change. This will allow previous version support but also allow up-to-date code without warnings

In other words, favor Proposal 3 while still allowing for support for older versions which are unlikely to change.

New applications should support iOS 10.0 and higher, but if they need to support an older version, they should use an older version of Swift
