### ISSUE TITLE
Add optional method that has unedited launchOptions?

### ISSUE THREAD

**Issue by dcvz** [square/SuperDelegate#7]
Unfortunately there's some SDK's that require the launchOptions directly. Maybe there could be an addition to have an optional protocol method that has these unedited launchOptions. I could not find any other built in work-around for this issue.

**Comment by dfed** [comment]
`LaunchItem` has a `launchOptions` getter that we built to solve this problem. Does that not do what you want? If not, can you give a concrete example for how it falls short?

**Comment by dfed** [comment]
Closing this. @dcvz if the `launchOpfions` accessor doesn't do what you need, please give me an example of how it's not working for you and I'll reopen.
