### ISSUE TITLE
Build fails when integrating through Cocoapods

### ISSUE THREAD

**Issue by gapl** [square/SuperDelegate#9]
As mentioned in the title, building the app fails in file `SuperDelegate+LocalNotifications.swift` on line `22`.

Error: `No such module 'UserNotifications'`.

My Podfile:

```
platform :ios, '8.0'

target 'NewProject' do
    use_frameworks!
    pod 'SuperDelegate'
end
```

Cocoapods version 1.0.1

**Comment by dfed** [comment]
Which version of Xcode are you using, and which release of SuperDelegate are you using? My guess is you are using 0.9.1 on Xcode 7. Per the README, Xcode 7 requires 0.8.1. The 0.9.* release is for those on the bleeding edge, e.g. Xcode 8.

**Comment by gapl** [comment]
Nice catch, I was in fact on Xcode 7.

I suggest adjusting the README for installation to not state `pod 'SuperDelegate'` but `pod 'SuperDelegate', '~> 0.8.1'` for others who miss that just like me 😊

Eager to give this one a go! Cheers.

**Comment by dfed** [comment]
Not a bad idea 🙂. Will do when I'm back at a computer

**Comment by dnkoutso** [comment]
I believe CocoaPods should introduce a `xcode_version` property to specify in podpecs.

There is one for `cocoapods_version` already but not for xcode.

**Comment by justinseanmartin** [comment]
I probably would've published xcode 8 support with breaking changes as a prerelease version so people don't get it accidentally (e.g. `~> 0.8.1-xcode8`). Also, as making breaking tool chain changes may even warrant a major version bump.

**Comment by dfed** [comment]
Pre-1.0 versioning is a little fuzzy for me. Was considering 0.9 a breaking change from 0.8 (this seems like a mistake in hindsight). Once we hit 1.0 we'll have a standard versioning system.
